import 'package:ayath_prayer_new/data/dua_name_item.dart';
import 'package:hive/hive.dart';

// Generated by `flutter packages pub run build_runner build`.
//flutter packages pub run build_runner build
part 'dua_category_item.g.dart';

@HiveType(typeId: 0)
class DuaCatergoryItem extends HiveObject {
  @HiveField(0)
  int? id;
  @HiveField(1)
  String name;
  @HiveField(2)
  int? time;
  @HiveField(3)
  int? totalDua;
  @HiveField(4)
  bool isFavourite;
  @HiveField(5)
  bool isDone;
  @HiveField(6)
  final DateTime createdAt;
  @HiveField(7)
  List<DuaNameItem> duaNameList;

  DuaCatergoryItem({
    this.id,
    required this.name,
    required this.duaNameList,
    this.isFavourite = false,
    required this.time,
    this.totalDua = 0,
    this.isDone = false,
    DateTime? createdAt,
  }) : this.createdAt = createdAt ?? DateTime.now();

  @override
  String toString() {
    return 'DuaCatergoryItem(id=$id, content=$name, isFavourite=$isFavourite, idDone=$isDone, createdAt=$createdAt)';
  }
}