import 'package:hive/hive.dart';

import 'dua_item.dart';

// Generated by `flutter packages pub run build_runner build`.
//flutter packages pub run build_runner build
part 'dua_name_item.g.dart';

@HiveType(typeId: 1)
class DuaNameItem extends HiveObject {
  @HiveField(0)
  int? id;
  @HiveField(1)
  String name;
  @HiveField(2)
  int? time;
  @HiveField(3)
  bool isFavourite;
  @HiveField(4)
  bool isDone;
  @HiveField(5)
  int? count;
  @HiveField(6)
  int? userCount;
  @HiveField(7)
  final DateTime createdAt;
  @HiveField(8)
  List<DuaItem> duaList;

  DuaNameItem({
    this.id,
    required this.name,
    required this.duaList,
    this.isFavourite = false,
    required this.time,
    this.userCount = 0,
    this.count = 0,
    this.isDone = false,
    DateTime? createdAt,
  }) : this.createdAt = createdAt ?? DateTime.now();

  @override
  String toString() {
    return 'TodoItem(id=$id, content=$name, idDone=$isDone, createdAt=$createdAt)';
  }
}
