import 'package:hive/hive.dart';

// Generated by `flutter packages pub run build_runner build`.
//flutter packages pub run build_runner build
part 'dua_item.g.dart';

@HiveType(typeId: 2)
class DuaItem extends HiveObject {
  @HiveField(0)
  int? id;
  @HiveField(1)
  String arabic;
  @HiveField(2)
  String translation;
  @HiveField(3)
  final DateTime createdAt;
  @HiveField(4)
  int? count;
  @HiveField(5)
  int? userCount;
  @HiveField(6)
  final DateTime updatedAt;


  DuaItem({
    this.id,
    required this.arabic,
    required this.translation,
    required this.count,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) :
        this.createdAt = createdAt ?? DateTime.now(),
        this.userCount = 0,
        this.updatedAt = updatedAt ?? DateTime.now()
  ;


  @override
  String toString() {
    return 'TodoItem(id=$id, createdAt=$createdAt)';
  }
}